site_name: AS-TestDataScience-2
site_description: Multivariate time series forecasting of home energy consumption using DL models
site_author: Antonio Squicciarini
repo_url: https://github.com/antosquicciarini/as-testdatascience-2
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Dataset & Features: data-overview.md
  - Models & Evaluation: models.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search